sudo: false
language: node_js
node_js:
- stable
branches:
  only:
  - master
deploy:
  provider: heroku
  app: diploma-work-sergey-timechenko
  api_key:
    secure: I2+MW0RUv6x89PVSmGDu7oTJ7yS4jl40DRWmEX8wibFBOTNjgLTUzoOMYI9NNG/FDi47RZkkqEXEuCvgPgFnCn2P9yPxs809cfb53bdTwl8fLQWBiYldu/JV2DwybOJIgQR0rXlmGnhgdfJpZClPS6Zkr/YGJbT/w1w05Bo8W8l9j/vstW/AoDF8uTwjUkwvFBUF1ri5y6kl4YOUVo2CN2rq4jDV8w3HFvygIieTOZthv9Qy3E6+Qm3+pVuXx5BOIQef+2W6JCpZDycQDKUCrXxLzxC9BMac3cz5iQsnzXaBtOSig9Cv86+XV0+F0tRZcByY0d912w4ptNpMZp4V+sYdPVDDHjknqYgWnyCqZ6k1wIDd0ephrmVR8Z2Qp8SKZGfXV+RusmgiTz6cOR/I4UNAzdzbN7tWV19cnf1Ent2TiXNHM/ZiSZ7tEZ9FKYPI1Ce+nLBZg86xbm6nGTA60jatbrUJiTt30IuePgIkmq0C7L3kRSNNX7B5NEEtabt1Np32sl7OM4RDwvm79TbtWqZYAsM/ZmvzGYtBInesfi81Pf3H/Ly7NGWyhDnx9CYbfIuHwppHTmIEonCc7LT0bSfNXOVNAF1TWUunRp5goSb7uA4iRGO0gnzHgu54ZL5XTX9ugdy5yiRpx56bL7mfu8wFNw1aGWEVgXW3b56Pjoo=
