env:
  global:
    - secure: "nIyKV7Nx6XDch7+2usOqNwMHc+s0cxjxdv92KnpEszSqW2Sv/nM6S/CRq4CsMl1FwOdU20MfsKmHQaktwS0XrXy6pPEcTH/Jn7aR+vleNqjVRcJUDIFWPjewXeoE/Q4g/iTodC0gjJPGs889Cv9uaT++ikkNnd9HVsD++nzu3ogixHZzbAN1LANOh9HZmBlb6IiiSlH4+hLyP0pQdBaWsy0rqm6A85HJklTT5Y48GWKdxFQHHcLg4lzMg3BcPIprVvew/yu1y529lY1bHLWxW6Blk79hnW6GKbhzL9Q37zrLtZ9MQ4b6OdZPbJCjPP5tesdbqA8tm58lN2VKNWDyTrEUu2vqsKR+dPQsWVqjFOWiY791E8ThldTINbd5JDP0hKmnR6c2eosgsSMa2I0YckC98SAjTMzz7j4YfihGsKSk3orDwO6j5bYI6R308tkhJP1X39CKWMnswXln5roSHcjgi5BwVZPuhyWwTcft2brWyLkfjE/XHnXxmIxccsmxokOKv7jPWoiF2J9zvl0p9bbbtJWVFXuVvwSZ8guef5IrT3HW4oNgO7xClSzA6q55i2/QFH7QfrR1WbVnGb27fGCR0T2GRj2QS62NKWitAhbmlDg1D6XMXpXJZ0rP82X55IJaocZGuEEpf+1cwdEAI9GtVc7syo4rO4O/pOXKE3E="

sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "diploma-work-sergey-timechenko"
  secure: HEROKU_API_KEY