sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master

env:
  global:
    secure: dAxy8NGpZKuXkP1dDRPVlB98zURRftZacE0BW+byb4+w1Ac/J1t6EPtDrCkQUJC03liK2z6AE10Tt2OUizLf3zFpNNNhFhf/82+telL0mNZBcZ6j5+vXQtOsw4zMdwDfRaDeG7nVXhv7C4LikriNHRuSVP+WkjjQ351f9giZ81jQKoZp/cztjv3ojKOJeh0OhaSAe759+9CWQVk/5T9wxg8y1CiUifBSHA47N5AWHUXvL0sL6TKhVeyqYtHXWKG2cGB8ldJbD1zHc2VhMz/dXQSwzbLWnOvVZB4HxtMElugaJv4DdbfqMeGVk1wQWNx4CPPZbdd1MnyPmVUNZjK73Op+cC1zzZSBjvCOV08PUGst1pfPaeSn8NwtngoW2/NL3FP033CtEwNdvNj3mmjAum7nATO6vlu7vPXV0vBN/dZx9mfuqwa5Mj3EwePpz6y2MTE6ffi1YLr3dJyl2oIIXVPXVWfkmMhphtYirtOp8t2Bn0fg7jfY8lrbOGHXQA+xTzCUuXL4vZ96Qtpq0xEyBL9rc5NZnFqY9HXrtw9l3PXOD/c3EQFfi6SYw20xjUSMmYvkMJlOxncTqmAhED2MpYgWsNjqCz+BPgfWADYlQjVzJTu4XyP1BvteZ8pUvP0JPPinUy2SnClW4ZJzOHc1CWxZJl9/MBn5D2ce03Auzak=

deploy:
  provider: heroku
  app: diploma-work-sergey-timechenko
  api_key:
    secure: dAxy8NGpZKuXkP1dDRPVlB98zURRftZacE0BW+byb4+w1Ac/J1t6EPtDrCkQUJC03liK2z6AE10Tt2OUizLf3zFpNNNhFhf/82+telL0mNZBcZ6j5+vXQtOsw4zMdwDfRaDeG7nVXhv7C4LikriNHRuSVP+WkjjQ351f9giZ81jQKoZp/cztjv3ojKOJeh0OhaSAe759+9CWQVk/5T9wxg8y1CiUifBSHA47N5AWHUXvL0sL6TKhVeyqYtHXWKG2cGB8ldJbD1zHc2VhMz/dXQSwzbLWnOvVZB4HxtMElugaJv4DdbfqMeGVk1wQWNx4CPPZbdd1MnyPmVUNZjK73Op+cC1zzZSBjvCOV08PUGst1pfPaeSn8NwtngoW2/NL3FP033CtEwNdvNj3mmjAum7nATO6vlu7vPXV0vBN/dZx9mfuqwa5Mj3EwePpz6y2MTE6ffi1YLr3dJyl2oIIXVPXVWfkmMhphtYirtOp8t2Bn0fg7jfY8lrbOGHXQA+xTzCUuXL4vZ96Qtpq0xEyBL9rc5NZnFqY9HXrtw9l3PXOD/c3EQFfi6SYw20xjUSMmYvkMJlOxncTqmAhED2MpYgWsNjqCz+BPgfWADYlQjVzJTu4XyP1BvteZ8pUvP0JPPinUy2SnClW4ZJzOHc1CWxZJl9/MBn5D2ce03Auzak=

